apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: ray-helm-chart
helmCharts:
  - name: kuberay-operator
    repo: https://ray-project.github.io/kuberay-helm/
    version: 1.0.0
    releaseName: kuberay-operator
